### ISSUE TITLE
iOS Icons

### ISSUE THREAD

**Issue by jimniels** [jimniels/jimniels.github.io#2]
@aspyre I tried to contact you via http://aspyreapps.com/contact but the contact form doesn't work. I couldn't find any contact information about you elsewhere on the web other than your GitHub account. So I'm trying to contact you here.

I run iOS Icon Gallery (http://www.iosicongallery.com) a website devoted to showcasing beautiful icon designs from the iOS ecosystem. I am working with the amazing icon designer Michael Flarup (https://twitter.com/flarup) to create a book showcasing the art of iOS icon design. You can read more about the project at https://www.appiconbook.com/

The reason I am reaching out to you is we would be flattered to include the "Photo Academy" icon in our book (http://www.iosicongallery.com/photo-academy-20110915/). Let me know if you'd be interested in helping us get your work in our book and I can provide more details.

Jim Nielsen

**Comment by aspyre** [comment]
Hey Jim,

Thanks for getting in touch. Apologies for the failed contact form - I've just gone through a site upgrade, and haven't managed to get the contact form working again as yet.

Sounds like a really neat project, and I'd certainly be happy to be included. Let me know what you need.

Cheers
Ben

**Comment by jimniels** [comment]
Fantastic, could you send me your email so I can communicate with you there? Mine is `jimniels` and that's at gmail.com
